name: Deployment to FirebaseHosting
on: workflow_dispatch
jobs:
  build_and_deploy:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [16]
    steps:
      - uses: actions/checkout@v3

      - name: Cache
        id: node_modules_cache_id
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ matrix.os }}-node-v${{ matrix.node }}-deps-${{ hashFiles(format('{0}{1}', github.workspace, '/package-lock.json')) }}

      - name: Install
        if: steps.node_modules_cache_id.outputs.cache-hit != 'true'
        run: |
          npm ci

      - name: Generate
        env:
          CMS_BASE_URL: ${{ secrets.CMS_BASE_URL }}
        run: |
          npm run build
          npm run generate

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_LUMINESS_WEB_25CBF }}"
          channelId: live
          projectId: luminess-web-25cbf
